Index: Python-Course/Code_samples/Python exception.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>def divide(a, b):\r\n    if b == 0:\r\n        raise ZeroDivisionError(\"Деление на ноль недопустимо\")\r\n    return a / b\r\n\r\n\r\ntry:\r\n    result = divide(10, 0)\r\n    print(result)\r\nexcept ZeroDivisionError as e:\r\n    print(f\"Ошибка: {e}\")\r\nfinally:\r\n    print(\"Завершение операции деления\")\r\n\r\n\r\n\r\ndef safe_divide(a, b):\r\n    return a / b\r\n\r\n# Основная часть программы\r\nprint(\"Начало программы\")\r\n\r\ntry:\r\n    # Код, который может вызвать исключение\r\n    result = safe_divide(10, 0)\r\n    print(f\"Результат: {result}\")\r\nexcept ZeroDivisionError:\r\n    # Обработка исключения\r\n    print(\"Ошибка: Деление на ноль недопустимо\")\r\n\r\nprint(\"Конец программы\")\r\n
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Python-Course/Code_samples/Python exception.py b/Python-Course/Code_samples/Python exception.py
--- a/Python-Course/Code_samples/Python exception.py	(revision 623d1655ead967e1f12d73638b897ac76e0dcb20)
+++ b/Python-Course/Code_samples/Python exception.py	(date 1737526835887)
@@ -29,3 +29,19 @@
     print("Ошибка: Деление на ноль недопустимо")
 
 print("Конец программы")
+
+
+def task_5():
+    a, b = input("Vvedite dve cifry oi duhi cerez probel:").split()
+    try:
+        x = int(a)/int(b)
+    except ZeroDivisionError:
+        print("Can't divide by zero")
+    except ValueError:
+        print("Entered value is wrong")
+    else:
+        print(x)
+    finally:
+        print("Vsio")
+
+task_5()
\ No newline at end of file
Index: Python-Course/Code_samples/test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>def task_5():\r\n    a, b = input(\"Vvedite dve cifry oi duhi cerez probel:\").split()\r\n    try:\r\n        x = int(a)/int(b)\r\n    except ZeroDivisionError:\r\n        print(\"Can't divide by zero\")\r\n    except ValueError:\r\n        print(\"Entered value is wrong\")\r\n    else:\r\n        print(x)\r\n    finally:\r\n        print(\"Vsio\")\r\n\r\ntask_5()
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Python-Course/Code_samples/test.py b/Python-Course/Code_samples/test.py
--- a/Python-Course/Code_samples/test.py	(revision 623d1655ead967e1f12d73638b897ac76e0dcb20)
+++ b/Python-Course/Code_samples/test.py	(date 1737528330489)
@@ -1,14 +1,10 @@
-def task_5():
-    a, b = input("Vvedite dve cifry oi duhi cerez probel:").split()
-    try:
-        x = int(a)/int(b)
-    except ZeroDivisionError:
-        print("Can't divide by zero")
-    except ValueError:
-        print("Entered value is wrong")
-    else:
-        print(x)
-    finally:
-        print("Vsio")
+print(dir(__builtins__))
+
 
-task_5()
\ No newline at end of file
+def get_builtins(a):
+    for i in __builtins__:
+        if i ==a:
+            print(i)
+
+
+print(get_builtins('AttributeError'))
Index: .gitignore.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>*.db\r\n*.log\r\ntarget/\r\nbin/
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.gitignore.txt b/.gitignore.txt
--- a/.gitignore.txt	(revision 623d1655ead967e1f12d73638b897ac76e0dcb20)
+++ b/.gitignore.txt	(date 1737501387313)
@@ -1,4 +1,5 @@
 *.db
 *.log
 target/
-bin/
\ No newline at end of file
+bin/
+.idea/
